FROM golang:1.27.1-alpine AS builder
WORKDIR /src
COPY go.mod go.sum ./
RUN go mod download
COPY . .
RUN CGO_ENABLED=0 GOMAXPROCS=2 go build -p 2 -trimpath -o /http-sms .

FROM alpine:3.22
RUN apk add --no-cache ca-certificates curl tzdata && addgroup -S httpsms && adduser -S httpsms -G httpsms
WORKDIR /home/httpsms
COPY --from=builder /http-sms ./http-sms
COPY root.crt ./root.crt
USER httpsms
ENTRYPOINT ["./http-sms", "--dotenv=false"]
